app/controllers/users_controller.rb, app/models/user.rb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20201013174255_create_users.rb, db/schema.rb, spec/features/users/show_spec.rb, spec/models/user_spec.rb
User Story 2, User Show Page
As a visitor
When I visit a User's show page
Then I see all that User's information
Including the User's
[x] - Name
[x] - Street Address
[x] - City
[x] - State
[x] - Zip
=> Userstory2

app/models/review.rb, app/models/shelter.rb, app/models/user.rb, app/views/shelters/show.html.erb, db/migrate/20201014002535_create_reviews.rb, db/migrate/20201014002607_add_users_to_reviews.rb, db/migrate/20201014002631_add_shelters_to_reviews.rb, db/schema.rb, db/seeds.rb, spec/features/shelters/show_spec.rb, spec/features/users/new_spec.rb, spec/models/review_spec.rb, spec/models/shelter_spec.rb, spec/models/user_spec.rb
User Story 4, Shelter Reviews
As a visitor,
When I visit a shelter's show page,
I see a list of reviews for that shelter
Each review will have:
[x]- title
[x]- rating
[x]- content
[x]- an optional picture
[x]- the name of the user that wrote the review
=> Userstory4

app/controllers/reviews_controller.rb, app/views/reviews/new.html.erb, app/views/shelters/show.html.erb, config/routes.rb, db/seeds.rb, spec/features/shelters/show_spec.rb
User Story 5, Shelter Review Creation
[ x ]
As a visitor,
When I visit a shelter's show page
I see a link to add a new review for this shelter.
When I click on this link, I am taken to a new review path
On this new page, I see a form where I must enter:
[ x ]- title
[ x ]- rating
[ x ]- content
[ x ]- the name of a user that exists in the database
I also see a field where I can enter an optional image (web address)
When the form is submitted, I should return to that shelter's show page
and I can see my new review
=> Userstory5

app/views/users/show.html.erb, spec/features/users/show_spec.rb
[x]- User Story 6, User Reviews
As a visitor
When I visit a User's show page
Then I see every review this User has written
Including the review's title, rating, and content
=> Userstory6

app/controllers/reviews_controller.rb, app/views/reviews/edit.html.erb
This PR:
- Updates the edit review form
- Updates flash messages
=> Userstory9

app/controllers/reviews_controller.rb, app/views/reviews/new.html.erb, spec/features/reviews/new_spec.rb
I still need to write the test but it works
=> Reviewrefactor

app/models/user.rb, app/views/users/show.html.erb, spec/features/users/show_spec.rb, spec/models/user_spec.rb
[ x] done
User Story 13, User Review Average Rating
As a visitor
When I visit a User's show page
Then I see the average rating of all of their reviews
=> Userstory13

app/models/application.rb, app/models/pet.rb, app/models/pet_application.rb, app/models/user.rb, app/views/users/show.html.erb, spec/features/users/show_spec.rb, spec/models/application_spec.rb, spec/models/pet_application_spec.rb, spec/models/pet_spec.rb, spec/models/user_spec.rb
[ x] done
User Story 14, Highlighted User Reviews
As a visitor
When I visit a User's show page
Then I see a section for "Highlighted Reviews"
And I see the review with the best rating that this user has written
And I see the review with the worst rating that this user has written
=> Userstory14

app/controllers/applications_controller.rb, app/models/user.rb, app/views/applications/show.html.erb, config/routes.rb, db/migrate/20201018165952_create_applications.rb, db/migrate/20201018173010_add_user_to_applications.rb, db/migrate/20201018173156_create_pet_applications.rb, db/migrate/20201018201420_remove_pets_from_applications.rb, db/schema.rb, db/seeds.rb, spec/features/applications/new_spec.rb, spec/models/user_spec.rb
[ x] done
User Story 15, Application Show Page
PAIR STORY: It is recommended that you work on this story as a pair. Both partners should understand the data model for applications and how they relate to other models.
As a visitor
When I visit an applications show page "/applications/:id"
Then I can see the following:
- Name of the User on the Application
- Full Address of the User on the Application
- Description of why the applicant says they'd be a good home for this pet(s)
- names of all pets that this application is for (all names of pets should be links to their show page)
- The Application's status, either "In Progress", "Pending", "Accepted", or "Rejected"
=> Userstory15

app/controllers/applications_controller.rb, app/models/application.rb, app/views/applications/user_validation.html.erb, app/views/pets/index.html.erb, config/routes.rb, spec/features/applications/new_spec.rb, spec/features/applications/show_spec.rb, spec/models/application_spec.rb
[ x] done
User Story 16, Starting an Application
As a visitor
When I visit the pet index page
Then I see a link to "Start an Application"
When I click this link
Then I am taken to the new application page where I see a form
When I fill in this form with my user name (assuming I have already created a user in the system)
And I click submit
Then I am taken to the new application's show page
And I see my user listed along with all of my address information
And I see an indicator that this application is "In Progress"
=> Userstory16

app/controllers/applications_controller.rb, spec/features/applications/new_spec.rb
[x ] done
User Story 17, Starting an Application, User not found
As a visitor
When I visit the new application page
And I fill in the form with the name of a User that doesn't exist in the database
And I click submit
Then I am taken back to the new applications page
And I see a message that the user could not be found.
=> Userstory17

app/controllers/applications_controller.rb, app/controllers/pets_controller.rb, app/views/applications/show.html.erb, spec/features/applications/new_spec.rb, spec/features/applications/show_spec.rb
[x ] done
User Story 18, Searching for Pets for an Application
As a visitor
When I visit an application's show page
And that application has not been submitted,
Then I see a section on the page to "Add a Pet to this Application"
In that section I see an input where I can search for Pets by name
When I fill in this field with a Pet's name
And I click submit,
Then I am taken back to the application show page
And under the search bar I see any Pet whose name matches my search
=> Userstory18

app/controllers/applications_controller.rb, app/controllers/pets_controller.rb, app/views/applications/show.html.erb, config/routes.rb, spec/features/applications/show_spec.rb
This PR:
- Reverts some changes made to userstory 19
- All tests passing
=> Userstory19edit

app/controllers/applications_controller.rb, app/views/applications/show.html.erb, config/routes.rb, spec/features/applications/show_spec.rb
[x] done
User Story 20, Submit an Application
As a visitor
When I visit an application's show page
And I have added one or more pets to the application
Then I see a section to submit my application
And in that section I see an input to enter why I would make a good owner for these pet(s)
When I fill in that input
And I click a button to submit this application
Then I am taken back to the application's show page
And I see an indicator that the application is "Pending"
And I see all the pets that I want to adopt
And I do not see a section to add more pets to this application
=> Userstory20

spec/features/applications/show_spec.rb
[X] done
User Story 21, No Pets on an Application
As a visitor
When I visit an application's show page
And I have not added any pets to the application
Then I do not see a section to submit my application
=> Add test for search without pets

app/controllers/applications_controller.rb, app/views/applications/show.html.erb, spec/features/applications/show_spec.rb
[X] done
User Story 22, Incomplete application for Pets
As a visitor
When I visit an application's show page
And I have added one or more pets to the application
And I fail to enter why I would make a good owner for these pet(s)
Then I am taken back to the application's show page
And I see a flash message that I need to fill out that field before I can submit the application
And I see my application is still "In Progress"
=> Userstory22

app/controllers/applications_controller.rb, spec/features/applications/show_spec.rb
[x ] done
User Story 23, Partial Matches for Pet Names
As a visitor
When visit an application show page
And I search for Pets by name
Then I see any pet whose name PARTIALLY matches my search
For example, if I search for "fluff", my search would match pets with names "fluffy", "fluff", and "mr. fluff"
=> Userstory23

app/assets/stylesheets/application.css
consumed another google api font
=> added some cool fonts for h2

app/controllers/admin_controller.rb, app/controllers/applications_controller.rb, app/controllers/shelterpets_controller.rb, app/models/application.rb, app/views/admin/show.html.erb, app/views/applications/show.html.erb, db/seeds.rb, spec/features/admin/show_spec.rb, spec/features/pets/delete_spec.rb, spec/models/application_spec.rb
[x] done
User Story 27, All Pets Accepted on an Application
As a visitor
When I visit an admin application show page
And I approve all pets for an application
Then I am taken back to the admin application show page
And I see the application's status has changed to "Approved"
=> User story 27

spec/features/reviews/incomplete_spec.rb
This PR:
- Adds a test for a review flash message
- All test passing
- Simplecov at 100%
=> Add test for review flash message

app/controllers/pet_applications_controller.rb, app/views/pet_applications/index.html.erb, app/views/pets/index.html.erb, app/views/pets/show.html.erb, config/routes.rb, spec/features/applications/show_spec.rb, spec/features/pet_applications/show_spec.rb, spec/features/reviews/incomplete_spec.rb
[X] done
User Story 30, Pet Applications Index Page
As a visitor
When I visit a pets show page
I see a link to view all applications for this pet
When I click that link
I can see a list of all the names of applicants for this pet
Each applicants name is a link to the application's show page
=> Userstory30

app/views/pet_applications/index.html.erb, spec/features/pet_applications/show_spec.rb
[X] done
User Story 31, Pet Applications Index Page When No Applications
As a visitor
When I visit a pet applications index page for a pet that has no applications on them
I see a message saying that there are no applications for this pet yet
=> Userstory31

app/views/pets/index.html.erb, app/views/shelters/index.html.erb, config/routes.rb
This PR:
- changes delete routes
- uses embedded ruby rather than html
- all tests passing
=> Change delete route to embedded ruby

app/controllers/admin_controller.rb, app/views/admin/show.html.erb, app/views/applications/show.html.erb, spec/features/admin/show_spec.rb
Did some code refactoring to make the status have a boolean like attribute and also display custom flash messages.
=> Brettrefactor
